feat: 自动更新版本
FEMessage/update-popup pull request #29
Opened 2020-10-20 09:35 UTC by gd4Ark

## Why
Why is this change required? What problem does it solve?

## How
Describe your steps:
1. one step
2. two step...

You may use xmind or other mind map to show you logic

## Test
Show your test case

you'd better show `before` and `after` 

## Docs
It there requires a change to the documentation？

2020-10-20 09:54 UTC, colmugx commented on README-zh.md
> +你也可以使用 [options.auto](#options.auto) 来实现自动更新版本。
文档不要人称代词可能会好些。这里
```suggestion
可以使用 [options.auto](#options.auto) 来实现自动更新版本。
```

上面那个“你需要”可以去掉

2020-10-20 10:20 UTC, colmugx commented on README.md
> +automatic update version，need to configure `options.versionType`.
set `options.versionType` to make updated version code automatic

2020-10-20 10:23 UTC, shoyuf approved these changes

2020-10-20 11:41 UTC, evillt commented on README.md
> +- Type: `boolean`
这里或许以 `auto: 什么方式` 会更直接些，即 `type auto = 'timestamp' | 未来支持更多`

这样就可以把 `versionType` 去掉了

2020-10-20 13:30 UTC, gd4Ark commented on README.md
> +- Type: `boolean`
有想过这种方式，只是 `auto` 这个命名如果是一个 `enum`  会有点奇怪吧？

2020-10-21 04:56 UTC, evillt commented on README.md
> +- Type: `boolean`
> 只是 auto 这个命名如果是一个 enum 会有点奇怪吧？

是有点奇怪

---

> 这里或许以 auto: 什么方式 会更直接些，即 type auto = 'timestamp' | 未来支持更多

我的**主观**是：我使用 auto 模式，以 timestamp 方式递增；就是当写入 auto 参数是就已经明确了 **开启** auto 模式

2020-10-23 08:35 UTC, levy9527 requested changes

2020-10-23 08:35 UTC, levy9527 commented on index.js
> +        this.options.versionType = 'timestamp'
timestamp 都重复出现几次了。

2020-10-23 08:55 UTC, gd4Ark commented on README.md
> +- Type: `boolean`
先这样吧🤒..

2020-10-23 09:00 UTC, levy9527 approved these changes

2020-10-23 09:02 UTC, merged